/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from 'react';
import { getOverrideProps } from '@aws-amplify/ui-react/internal';
import { Text, View } from '@aws-amplify/ui-react';
import Profile from './Profile';
export default function SideNavigation(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="315px"
      height="812px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      overflow="hidden"
      position="relative"
      borderRadius="0px 30px 30px 0px"
      padding="0px 0px 0px 0px"
      backgroundColor="rgba(0,40,107,1)"
      {...getOverrideProps(overrides, 'SideNavigation')}
      {...rest}>
      <Text
        fontFamily="Lato"
        fontSize="16px"
        fontWeight="600"
        color="rgba(255,255,255,1)"
        lineHeight="19.200000762939453px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="253px"
        left="30px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Home"
        {...getOverrideProps(overrides, '\u270F\uFE0F Menu 1')}></Text>
      <Text
        fontFamily="Lato"
        fontSize="16px"
        fontWeight="600"
        color="rgba(255,255,255,1)"
        lineHeight="19.200000762939453px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="302px"
        left="30px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Order"
        {...getOverrideProps(overrides, '\u270F\uFE0F Menu 2')}></Text>
      <Text
        fontFamily="Lato"
        fontSize="16px"
        fontWeight="600"
        color="rgba(255,255,255,1)"
        lineHeight="19.200000762939453px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="351px"
        left="30px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Saved Place"
        {...getOverrideProps(overrides, '\u270F\uFE0F Menu 3')}></Text>
      <Text
        fontFamily="Lato"
        fontSize="16px"
        fontWeight="600"
        color="rgba(255,255,255,1)"
        lineHeight="19.200000762939453px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="400px"
        left="30px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Community"
        {...getOverrideProps(overrides, '\u270F\uFE0F Menu 4')}></Text>
      <Text
        fontFamily="Lato"
        fontSize="16px"
        fontWeight="600"
        color="rgba(255,255,255,1)"
        lineHeight="19.200000762939453px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="449px"
        left="30px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Support"
        {...getOverrideProps(overrides, '\u270F\uFE0F Menu 5')}></Text>
      <Text
        fontFamily="Lato"
        fontSize="16px"
        fontWeight="600"
        color="rgba(255,255,255,1)"
        lineHeight="19.200000762939453px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="498px"
        left="30px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Settings"
        {...getOverrideProps(overrides, '\u270F\uFE0F Menu 6')}></Text>
      <Text
        fontFamily="Lato"
        fontSize="16px"
        fontWeight="600"
        color="rgba(255,255,255,1)"
        lineHeight="19.200000762939453px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="547px"
        left="30px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Settings"
        {...getOverrideProps(overrides, '\u270F\uFE0F Menu 7')}></Text>
      <Text
        fontFamily="Lato"
        fontSize="16px"
        fontWeight="600"
        color="rgba(239,53,97,1)"
        lineHeight="19.200000762939453px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        bottom="43px"
        left="30px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Logout"
        {...getOverrideProps(overrides, '\u270F\uFE0F Menu 8')}></Text>
      <View
        width="5px"
        height="50px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="381px"
        left="290px"
        borderRadius="2.5px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(245,249,255,1)"
        {...getOverrideProps(overrides, 'Controller')}></View>
      <Profile
        width="315px"
        height="89px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="104px"
        left="0px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(25,61,122,1)"
        {...getOverrideProps(overrides, 'Profile')}></Profile>
    </View>
  );
}
